name: closed_deliver
description: "CloseExp application for delivery staff"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State Management - BLoC Pattern
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Network & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

  # Local Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.4

  # Functional Programming
  dartz: ^0.10.1

  # Navigation
  go_router: ^14.6.2

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  mapbox_maps_flutter: ^2.6.0
  connectivity_plus: ^7.0.0
  device_preview: ^1.2.0
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/navigations/
    - assets/icons/icon_bottoms/
    - assets/icons/qr_scan/
  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/DMSans-Italic-VariableFont_opsz,wght.ttf
          style: italic
